## Load Dataset

In [31]:
import pandas as pd

In [32]:
messages = pd.read_csv("SpamClassifier-master/smsspamcollection/SMSSpamcollection",sep='\t',names=['label','message'])

In [33]:
messages.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [34]:
messages.tail()

     label                                            message
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

In [35]:
import nltk
import re 
from nltk.corpus import stopwords 
from nltk.stem import WordNetLemmatizer

In [36]:
lemmetizer = WordNetLemmatizer()

In [37]:
corpus = []
for i in range(0,len(messages)):
    review = re.sub('^[a-zA-Z]',' ',messages['message'][i])
    review = review.lower()
    review = review.split()
    review = [lemmetizer.lemmatize(word,pos='v') for word in review if word not in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [38]:
corpus

['jurong point, crazy.. available bugis n great world la e buffet... cine get amore wat...',
 'k lar... joke wif u oni...',
 "ree entry 2 wkly comp win fa cup final tkts 21st may 2005. text fa 87121 receive entry question(std txt rate)t&c's apply 08452810075over18's",
 'dun say early hor... u c already say...',
 'ah think go usf, live around though',
 "reemsg hey darling 3 week's word back! like fun still? tb ok! xxx std chgs send, £1.50 rcv",
 'ven brother like speak me. treat like aid patent.',
 "per request 'melle melle (oru minnaminunginte nurungu vettam)' set callertune callers. press *9 copy friends callertune",
 'inner!! value network customer select receivea £900 prize reward! claim call 09061701461. claim code kl341. valid 12 hours only.',
 'ad mobile 11 months more? u r entitle update latest colour mobiles camera free! call mobile update co free 08002986030',
 "'m gonna home soon want talk stuff anymore tonight, k? cry enough today.",
 'ix chance win cash! 100 20,000 pound txt> csh11 send 87575. cost 150p/day, 6days, 16+ tsandcs apply reply hl 4 info',
 'rgent! 1 week free membership £100,000 prize jackpot! txt word: claim no: 81010 t&c www.dbuk.net lccltd pobox 4403ldnw1a7rw18',
 "'ve search right word thank breather. promise wont take help grant fulfil promise. wonderful bless times.",
 'date sunday will!!',
 'xxmobilemovieclub: use credit, click wap link next txt message click here>> http://wap. xxxmobilemovieclub.com?n=qjkgighjjgcbl',
 "h k...i'm watch here:)",
 'h u remember 2 spell name... yes did. v naughty make v wet.',
 'ine that\x92s way u feel. that\x92s way gota b',
 'ngland v macedonia - dont miss goals/team news. txt ur national team 87077 eg england 87077 try:wales, scotland 4txt/ú1.20 poboxox36504w45wq 16+',
 'seriously spell name?',
 '‘m go try 2 months ha ha joke',
 'ü pay first lar... da stock comin...',
 'ft finish lunch go str lor. ard 3 smth lor. u finish ur lunch already?',
 'fffffffff. alright way meet sooner?',
 'ust force eat slice. really hungry tho. sucks. mark get worried. know sick turn pizza. lol',
 'ol always convincing.',
 "id catch bus ? fry egg ? make tea? eat mom's leave dinner ? feel love ?",
 "'m back &amp; pack car now, let know there's room",
 'hhh. work. vaguely remember that! feel like? lol',
 "ait that's still clear, sure sarcastic that's x want live us",
 'eah get 2 v apologetic. n fall actin like spoil child get catch that. till 2! go there! badly cheers. you?',
 'tell anything you.',
 'fear faint housework did? quick cuppa',
 'hanks subscription ringtone uk mobile charge £5/month please confirm reply yes no. reply charge',
 'up... ok go home look timings msg ü again... xuhui go learn 2nd may lesson 8am',
 "ops, let know roommate's do",
 'see letter b car',
 'nything lor... u decide...',
 "ello! how's saturday go? texting see decide anything tomo. try invite anything!",
 'ls go ahead watts. want sure. great weekend. abiola',
 'id forget tell ? want , need you, crave ... ... love sweet arabian steed ... mmmmmm ... yummy',
 '07732584351 - rodger burn - msg = try call reply sms free nokia mobile + free camcorder. please call 08000930705 delivery tomorrow',
 'ho seeing?',
 'reat! hope like man well endowed. &lt;#&gt; inches...',
 'calls..messages..missed call',
 "idn't get hep b immunisation nigeria.",
 'air enough, anything go on?',
 "eah hopefully, tyler can't could maybe ask around bite",
 'know stubborn am. even want go hospital. keep tell mark weak sucker. hospitals weak suckers.',
 'hat think me. first time saw class.',
 'gram usually run like &lt;#&gt; , half eighth smarter though get almost whole second gram &lt;#&gt;',
 'fyi x ride early tomorrow morning crash place tonight',
 'ow. never realize embarassed accomodations. think like it, since best could always seem happy "the cave". sorry give. sorry offered. sorry room embarassing.',
 'ms. ac sptv: new jersey devil detroit red wing play ice hockey. correct incorrect? end? reply end sptv',
 'know mallika sherawat yesterday? find @ &lt;url&gt;',
 'ongrats! 1 year special cinema pass 2 yours. call 09061209465 now! c suprman v, matrix3, starwars3, etc 4 free! bx420-ip4-5we. 150pm. dont miss out!',
 'orry, call later meeting.',
 'ell reach',
 'es..gauti sehwag odi series.',
 "gonna pick $1 burger way home. can't even move. pain kill me.",
 'ha ha good joke. girls situation seekers.',
 'ts part check iq',
 'orry roommates take forever, ok come now?',
 'k lar double check wif da hair dresser already say wun cut v short. say cut look nice.',
 'value customer, please advise follow recent review mob no. award £1500 bonus prize, call 09066364589',
 'oday "song dedicate day.." song u dedicate me? send ur valuable frnds first rply me...',
 'rgent ur award complimentary trip eurodisinc trav, aco&entry41 £1000. claim txt dis 87121 18+6*£1.50(morefrmmob. shracomorsglsuplt)10, ls1 3aj',
 'id hear new "divorce barbie"? come ken\'s stuff!',
 'plane give month end.',
 'ah lucky man... save money... hee...',
 'inished class you.',
 'babe im home wanna something? xx',
 '..k:)where you?how performed?',
 'call now...',
 'wait machan. call free.',
 'hat cool. gentleman treat dignity respect.',
 'like people much:) shy pa.',
 'oes operate &lt;#&gt;',
 "ts here. still look job. much ta's earn there.",
 'orry, call later',
 '. call ah?',
 'k way home hi hi',
 'ou place man',
 'next stop.',
 'call later, network. urgnt, sms me.',
 'real u get yo? need 2 ticket one jacket done. already use multis.',
 'es start send request make pain come back back bed. double coin factory too. gotta cash nitros.',
 "'m really still tonight babe",
 'la kano.,il download, come wen ur free..',
 'eah do! don‘t stand close tho- you‘ll catch something!',
 'orry pain. ok meet another night? spend late afternoon casualty mean do stuff42moro include time sheet that. sorry.',
 'mile pleasure smile pain smile trouble pour like rain smile sum1 hurt u smile becoz someone still love see u smiling!!',
 'lease call customer service representative 0800 169 6031 10am-9pm guarantee £1000 cash £5000 prize!',
 'avent plan buy later. check already lido get 530 show e afternoon. u finish work already?',
 'free ringtone wait collected. simply text password "mix" 85069 verify. get usher britney. fml, po box 5249, mk17 92h. 450ppw 16',
 'atching telugu movie..wat abt u?',
 'see. finish load loan pay',
 'i. wk ok - hols now! yes bite run. forget hairdressers appointment four need get home n shower beforehand. cause prob u?"',
 'see cup coffee animation',
 'lease text anymore. nothing else say.',
 'kay name ur price long legal! wen pick up? u ave x ams xx',
 "'m still look car buy. go 4the drive test yet.",
 "per request 'melle melle (oru minnaminunginte nurungu vettam)' set callertune callers. press *9 copy friends callertune",
 'ow. right! mean that. guess give boston men change search location nyc, something changed. cuz signin page still say boston.',
 'mma life vava umma love lot dear',
 'hanks lot wish birthday. thank make birthday truly memorable.',
 'ight, hit get cash',
 'ow would ip address test consider computer minecraft server',
 'know! grumpy old people. mom like better lying. always one play jokes...',
 'ont worry. guess busy.',
 'hat plural noun research?',
 'oing dinner.msg after.',
 "'m ok wif cos like 2 try new things. scar u dun like mah. cos u say loud.",
 'ent! try contact you. last weekend draw show £1000 prize guaranteed. call 09064012160. claim code k52. valid 12hrs only. 150ppm',
 'a, ur openin sentence formal... anyway, fine too, juz tt eatin much n puttin weight...haha... anythin special happened?',
 "enter cabin pa said, '' happy b'day boss !!''. felt special. askd 4 lunch. lunch invite apartment. go there.",
 'ou winner u specially select 2 receive £1000 4* holiday (flights inc) speak live operator 2 claim 0871277810910p/min (18+)',
 'oodo! yes must speak friday - egg-potato ratio tortilla needed!',
 'mm...my uncle inform pay school directly. pls buy food.',
 'rivate! 2004 account statement 07742676969 show 786 unredeemed bonus points. claim call 08719180248 identifier code: 45239 expire',
 'rgent! mobile no. award £2000 bonus caller prize 5/9/03 final try contact u! call landline 09064019788 box42wr29c, 150ppm',
 'ere new address -apples&pairs&all malarky',
 'odays voda number end 7548 select receive $350 award. match please call 08712300220 quote claim code 4041 standard rat app',
 'go sao mu today. do 12',
 "ü predict wat time ü'll finish buying?",
 'ood stuff, do.',
 'ust know,yetunde send money yet. send text bother sending. over, dont involve anything. impose anything first place that, apologise.',
 'room.',
 'ey girl. r u? hope u r well del r bak! long time c! give call sum time lucyxx',
 '..k:)how much cost?',
 "'m home.",
 'ear, call tmorrow.pls accomodate.',
 'irst answer question.',
 'unshine quiz wkly q! win top sony dvd player u know country algarve in? txt ansr 82277. £1.50 sp:tyrone',
 "ant 2 get lay tonight? want real dog locations send direct 2 ur mob? join uk's largest dog network bt txting gravel 69888! nt. ec2a. 31p.msg@150p",
 'haf msn. yijue@hotmail.com',
 'e there. call meet',
 'no. check room befor activities',
 "ou'll rcv msgs chat svc. free hardcore service text go to: 69988 u get nothing u must age verify yr network & try",
 'ot c... lazy type... forget ü lect... saw pouch like v nice...',
 ', text way',
 'ir, wait mail.',
 'swt thought: "nver get tire little things 4 lovable persons.." coz..somtimes little things occupy biggest part hearts.. gud ni8',
 'know are. pls open back?',
 'es see ya dot',
 'hat staff name take class us?',
 'reemsg reply text? randy, sexy, female live local. luv hear u. netcollex ltd 08700621170150p per msg reply stop end',
 'mmma.will call check in.our life begin qatar pls pray hard.',
 '..i delete contact why?',
 'indu get job birla soft ..',
 'wine flow nevering..',
 'thk cine better cos need 2 go 2 plaza mah.',
 'k... ur typical reply...',
 "per request 'melle melle (oru minnaminunginte nurungu vettam)' set callertune callers. press *9 copy friends callertune",
 'ou everywhere dirt, floor, windows, even shirt. sometimes open mouth, come flow out. dream world without you, half chores too. time joy me, lot tv show i.ll see. guess like things must exist, like rain, hail mist, time done, become one.',
 'aooooright work?',
 "'m leave house now...",
 'ello, love. doing? get interview today? happy? good boy? think me?are miss ?',
 'ustomer service annoncement. new years delivery wait you. please call 07046744435 arrange delivery',
 'ou winner u specially select 2 receive £1000 cash 4* holiday (flights inc) speak live operator 2 claim 0871277810810',
 "eep safe need miss already envy everyone see's real life",
 'ew car house parents.:)i new job hand:)',
 "'m love you. excite day spend you. make happy.",
 '-pls stop bootydelious (32/f) invite friend. reply yes-434 no-434 see her: www.sms.ac/u/bootydelious stop? send stop frnd 62468',
 'angbabes ur order way. u receive service msg 2 download ur content. u not, goto wap. bangb. tv ur mobile internet/service menu',
 'place ur point e culture module already.',
 'rgent! try contact you. last weekend draw show £900 prize guaranteed. call 09061701939. claim code s89. valid 12hrs',
 "frnd, best way avoid missunderstding wit beloved one's?",
 'reat escape. fancy bridge need lager. see tomo',
 'es :)it completely form:)clark also utter waste.',
 'ir, need axis bank account bank address.',
 'mmm.. thk sure get time hop ard... ya, go 4 free abt... muz call u discuss liao...',
 'hat time come later?',
 'loody hell, cant believe forget surname mr . ill give u clue, spanish begin m...',
 'ell, gonna finish bath now. good...fine night.',
 'et know get money carlos make call',
 'still go mall?',
 'urns friends stay whole show back til ~ &lt;#&gt; , feel free go ahead smoke $ &lt;#&gt; worth',
 'ext her. doesnt reply let know log',
 'i! speak maneesha v. like know satisfy experience. reply toll free yes no.',
 'ou lift hop offer money. need. especially end month approach hurt studying. anyways gr8 weekend',
 'ol no. u trust me.',
 'k. gentleman treat dignity respect.',
 'e will, guy close?',
 'oing nothing great.bye',
 "ello handsome ! find job ? lazy ? work towards get back net mummy ? where's boytoy ? miss ?",
 'aha awesome, minute',
 'lease call customer service representative freephone 0808 145 4742 9am-11pm guarantee £1000 cash £5000 prize!',
 'ave get xmas radio times. get',
 'jus reach home. go bathe first. sis use net tell u finish k...',
 'unique enough? find 30th august. www.areyouunique.co.uk',
 "'m sorry. join league people dont keep touch. mean great deal me. friend time even great personal cost. great week.|",
 ':)finally complete course:)',
 'stop itself. however suggest stay someone able give ors every stool.',
 'ow doing? hope settle new school year. wishin gr8 day',
 'ud mrng dear hav nice day',
 'id u get persons story',
 'hamster dead? hey tmr meet 1pm orchard mrt?',
 'kate evening? hope see tomorrow bite bloody babyjontet! txt back u can. :) xxx',
 'ound it, enc &lt;#&gt; , at?',
 'send &lt;#&gt; buck',
 'ello darlin ive finish college txt u finish u love kate xxx',
 'account refill successfully inr &lt;decimal&gt; . keralacircle prepay account balance rs &lt;decimal&gt; . transaction id kr &lt;#&gt; .',
 'oodmorning sleep ga.',
 'call alter 11 ok.',
 'ü say like dat dun buy ericsson oso cannot oredi lar...',
 "enter cabin pa said, '' happy b'day boss !!''. felt special. askd 4 lunch. lunch invite apartment. go there.",
 'ight yo, dats straight dogg',
 'ou please give us connection today &lt;decimal&gt; refund bill',
 'oth :) shoot big load get ready!',
 "hat's bruv, hope great break. reward semester.",
 'ome always chat',
 ':)k:)good:)study well.',
 'up... ü noe leh...',
 'ounds great! home now?',
 'inally match head towards draw prediction.',
 'ired. sleep well past nights.',
 'asy ah?sen get select mean good..',
 'take exam march 3',
 "eah should. think use gt atm register. sure there's anyway help let know. sure ready.",
 'k prob. take ur time.',
 'os call ubandu run without instal hard disk...you use os copy important file system give repair shop..',
 'orry, call later',
 'say leh... course nothing happen lar. say v romantic jus bite lor. thk e nite scenery nice leh.',
 '500 new mobiles 2004, must go! txt: nokia no: 89545 & collect today!from £1 www.4-tc.biz 2optout 087187262701.50gbp/mtmsg18',
 'ould really appreciate call me. need someone talk to.',
 'ill u meet ur dream partner soon? ur career 2 flyng start? 2 find free, txt horo follow ur star sign, e. g. horo aries',
 'ey company elama po mudyadhu.',
 'ife strict teacher... bcoz teacher teach lesson &amp; conduct exam, life first conduct exam &amp; teach lessons. happy morning. . .',
 'ear good morning',
 'et gandhipuram walk cross cut road. right side &lt;#&gt; street road turn first right.',
 'ear go rubber place',
 'orry battery died, yeah',
 'es:)here tv always available work place..',
 'ext & meet someone sexy today. u find date even flirt u. join 4 10p. reply name & age eg sam 25. 18 -msg recd@thirtyeight pence',
 'print oh. &lt;#&gt; come upstairs',
 'r ill little closer like bus stop street',
 'you?when wil reach here?',
 'ew theory: argument win situation, lose person. dont argue ur friends just.. . . . kick &amp; say, always correct.!',
 '447801259231 secret admirer look 2 make contact u-find r*reveal think ur special-call 09058094597',
 'omarrow final hear laptop case cant.',
 'leassssssseeeeee tel v avent do sportsx',
 'kay. no, shin on. mean signing, sound better.',
 "lthough tell u dat baig face watch really like e watch u give cos fr u. thanx 4 everything dat u've do today, touched...",
 'remember old commercial?',
 'oo late. say website. dont slippers',
 'ask call ok',
 'allis wont bat 2nd innings.',
 'didnt work oh. ok goodnight then. i.ll fix ready time wake up. dearly miss good night sleep.',
 'ongratulations ur award 500 cd vouchers 125gift guarantee & free entry 2 100 wkly draw txt music 87066 tncs www.ldew.com1win150ppmx3age16',
 'anjith cal drpd deeraj deepak 5min hold',
 'en ur lovable bcums angry wid u, dnt take seriously.. coz angry childish n true way show deep affection, care n luv!.. kettoda manda... nice day da.',
 'hat doing?how you?',
 'ps 3days also, ship company take 2wks. way usps take week get lag may bribe nipost get stuff.',
 "'m back, lemme know ready",
 "on't necessarily expect do get back though headin",
 'mm yummy babe ... nice jolt suzy',
 'lover ? need ...',
 'e try contact reply offer video handset? 750 anytime network mins? unlimited text? camcorder? reply call 08000930705',
 '‘m park next mini!!!! come today think?',
 '',
 'nyway go shop now. cos sis do yet. dun disturb u liao.',
 'no. luton 0125698789 ring ur around! h*',
 'ey really horny want chat see naked text hot 69698 text charge 150pm unsubscribe text stop 69698',
 'hy dint come us.',
 'ame. wana plan trip sometme',
 'ot sure yet, still try get hold',
 'r ringtone service changed! 25 free credits! go club4mobiles.com choose content now! stop? txt club stop 87070. 150p/wk club4 po box1146 mk45 2wt',
 'evo. download flash. jealous?',
 'ingtone club: get uk single chart mobile week choose top quality ringtone! message free charge.',
 'ome mu, sort narcotics situation',
 'ight end another day, morning come special way. may smile like sunny ray leave worry blue blue bay.',
 'mv bonus special 500 pound genuine hmv vouchers won. answer 4 easy questions. play now! send hmv 86688 info:www.100percent-real.com',
 'sf guess, might well take 1 car',
 'objection. bf coming.',
 'hanx...',
 'ell rob mack gf theater',
 'wesome, see bite',
 'ust send it. type food like?',
 'done? hand in? celebrations full swing yet?',
 'ou get call tool?',
 'en u miss someone, person definitely special u..... person special, miss them, keep-in-touch gdeve..',
 'k. ask money far',
 'kie...',
 "eah think usual guy's still pass last night, get ahold anybody let know throw",
 ', might come tonight class let early',
 'k..',
 'baby im cruisin girl friend r u 2? give call hour home thats alright fone fone love jenny xxx',
 'life mean lot me, love life, love people life, world call friends, call world:-).. ge:-)..',
 'ear,shall mail tonite.busy street,shall update tonite.things look ok.varunnathu edukkukayee raksha ollu.but good one real sense.',
 'ey tell name gautham ah?',
 'af u find him? feel stupid da v cam working.',
 'ops. 4 get bit.',
 'much buzy',
 'accidentally delete message. resend please.',
 "-mobile customer may claim free camera phone upgrade & pay & go sim card loyalty. call 0845 021 3680.offer end 28thfeb.t&c's apply",
 'nless situation go gurl would appropriate',
 'urt me... tease me... make cry... end life die plz keep one rise grave say stupid miss u.. nice day bslvyl',
 'cant pick phone right now. pls send message',
 "eed coffee run tomo?can't believe time week already",
 'wesome, remember last time get somebody high first time diesel :v',
 'hit really shock scary, cant imagine second. def night out. u think somewhere could crash night, save taxi?',
 'h way food fridge! want go meal tonight?',
 'e womdarfull actor',
 'ms. ac blind date 4u!: rodds1 21/m aberdeen, unite kingdom. check http://img. sms. ac/w/icmb3cktz8r7!-4 blind date send hide',
 'up... remb... think book...',
 'os ask u wana meet up?',
 'ol yes. friendship hang thread cause u buy stuff.',
 'hemob> check newest selection content, games, tones, gossip, babes sport, keep mobile fit funky text wap 82468',
 'garage keys? bookshelf',
 'oday accept day..u accept as? brother sister lover dear1 best1 clos1 lvblefrnd jstfrnd cutefrnd lifpartnr belovd swtheart bstfrnd rply mean enemy',
 'hink ur smart ? win £200 week weekly quiz, text play 85222 now!t&cs winnersclub po box 84, m26 3uz. 16+. gbp1.50/week',
 "e say give call friend's get money definitely buy end week",

## Create Bag Of Words

In [39]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500,ngram_range = (1,2))

In [40]:
X = cv.fit_transform(corpus).toarray()

In [41]:
import numpy as np

In [42]:
np.set_printoptions(edgeitems=30,linewidth=100000,formatter=dict(float=lambda x:"%0.3g" % x))
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], shape=(5572, 2500))

In [43]:
cv.vocabulary_

{'point': np.int64(1713),
 'crazy': np.int64(560),
 'available': np.int64(266),
 'bugis': np.int64(366),
 'great': np.int64(935),
 'world': np.int64(2450),
 'la': np.int64(1173),
 'cine': np.int64(473),
 'get': np.int64(862),
 'wat': np.int64(2363),
 'lar': np.int64(1183),
 'joke': np.int64(1144),
 'wif': np.int64(2415),
 'ree': np.int64(1801),
 'entry': np.int64(725),
 'wkly': np.int64(2437),
 'comp': np.int64(518),
 'win': np.int64(2420),
 'cup': np.int64(574),
 'final': np.int64(793),
 'may': np.int64(1334),
 'text': np.int64(2120),
 'receive': np.int64(1793),
 'question': np.int64(1759),
 'std': np.int64(2045),
 'txt': np.int64(2227),
 'rate': np.int64(1773),
 'apply': np.int64(226),
 'ree entry': np.int64(1803),
 'txt rate': np.int64(2231),
 'rate apply': np.int64(1774),
 'dun': np.int64(679),
 'say': np.int64(1889),
 'early': np.int64(692),
 'already': np.int64(195),
 'ah': np.int64(177),
 'think': np.int64(2141),
 'go': np.int64(900),
 'usf': np.int64(2296),
 'live': np.int64(1248),
 'around': np.int64(241),
 'though': np.int64(2151),
 'think go': np.int64(2143),
 'reemsg': np.int64(1805),
 'hey': np.int64(1016),
 'darling': np.int64(590),
 'week': np.int64(2380),
 'word': np.int64(2444),
 'back': np.int64(288),
 'like': np.int64(1234),
 'fun': np.int64(847),
 'still': np.int64(2047),
 'ok': np.int64(1551),
 'xxx': np.int64(2470),
 'send': np.int64(1919),
 '50': np.int64(103),
 'brother': np.int64(361),
 'speak': np.int64(2023),
 'me': np.int64(1337),
 'treat': np.int64(2204),
 'per': np.int64(1655),
 'request': np.int64(1828),
 'melle': np.int64(1348),
 'set': np.int64(1939),
 'callertune': np.int64(409),
 'callers': np.int64(407),
 'press': np.int64(1734),
 'copy': np.int64(540),
 'friends': np.int64(834),
 'per request': np.int64(1659),
 'set callertune': np.int64(1940),
 'callertune callers': np.int64(410),
 'callers press': np.int64(408),
 'press copy': np.int64(1735),
 'copy friends': np.int64(541),
 'friends callertune': np.int64(835),
 'value': np.int64(2307),
 'network': np.int64(1470),
 'customer': np.int64(579),
 'select': np.int64(1913),
 '900': np.int64(142),
 'prize': np.int64(1741),
 'reward': np.int64(1839),
 'claim': np.int64(476),
 'call': np.int64(386),
 'code': np.int64(494),
 'valid': np.int64(2305),
 '12': np.int64(40),
 'hours': np.int64(1052),
 'only': np.int64(1570),
 '900 prize': np.int64(143),
 'claim call': np.int64(478),
 'claim code': np.int64(479),
 'ad': np.int64(160),
 'mobile': np.int64(1394),
 '11': np.int64(37),
 'months': np.int64(1417),
 'more': np.int64(1422),
 'entitle': np.int64(723),
 'update': np.int64(2264),
 'latest': np.int64(1193),
 'colour': np.int64(503),
 'mobiles': np.int64(1405),
 'camera': np.int64(415),
 'free': np.int64(820),
 'co': np.int64(491),
 'ad mobile': np.int64(161),
 'entitle update': np.int64(724),
 'update latest': np.int64(2266),
 'latest colour': np.int64(1195),
 'free call': np.int64(822),
 'call mobile': np.int64(399),
 'mobile update': np.int64(1404),
 'update co': np.int64(2265),
 'co free': np.int64(492),
 'gonna': np.int64(918),
 'home': np.int64(1037),
 'soon': np.int64(2016),
 'want': np.int64(2352),
 'talk': np.int64(2101),
 'stuff': np.int64(2067),
 'anymore': np.int64(217),
 'tonight': np.int64(2187),
 'cry': np.int64(567),
 'enough': np.int64(720),
 'today': np.int64(2173),
 'want talk': np.int64(2359),
 'chance': np.int64(452),
 'cash': np.int64(436),
 '100': np.int64(28),
 '20': np.int64(60),
 '000': np.int64(2),
 'pound': np.int64(1726),
 'cost': np.int64(544),
 '150p': np.int64(47),
 'day': np.int64(595),
 '16': np.int64(52),
 'reply': np.int64(1821),
 'hl': np.int64(1027),
 'info': np.int64(1101),
 'chance win': np.int64(454),
 'cost 150p': np.int64(546),
 'reply hl': np.int64(1823),
 'rgent': np.int64(1840),
 'no': np.int64(1492),
 'www': np.int64(2461),
 'net': np.int64(1468),
 'pobox': np.int64(1707),
 'week free': np.int64(2382),
 'txt word': np.int64(2233),
 've': np.int64(2309),
 'search': np.int64(1899),
 'right': np.int64(1846),
 'thank': np.int64(2129),
 'promise': np.int64(1752),
 'wont': np.int64(2443),
 'take': np.int64(2098),
 'help': np.int64(1009),
 'wonderful': np.int64(2442),
 'bless': np.int64(332),
 'times': np.int64(2164),
 'date': np.int64(593),
 'sunday': np.int64(2079),
 'will': np.int64(2419),
 'use': np.int64(2294),
 'credit': np.int64(562),
 'click': np.int64(486),
 'wap': np.int64(2360),
 'link': np.int64(1244),
 'next': np.int64(1481),
 'message': np.int64(1354),
 'here': np.int64(1015),
 'http': np.int64(1059),
 'com': np.int64(505),
 'watch': np.int64(2366),
 'remember': np.int64(1815),
 'name': np.int64(1457),
 'yes': np.int64(2481),
 'did': np.int64(624),
 'naughty': np.int64(1461),
 'make': np.int64(1309),
 'wet': np.int64(2399),
 'ine': np.int64(1100),
 'that': np.int64(2132),
 'way': np.int64(2370),
 'feel': np.int64(782),
 'dont': np.int64(657),
 'miss': np.int64(1378),
 'team': np.int64(2107),
 'news': np.int64(1480),
 'ur': np.int64(2267),
 'national': np.int64(1458),
 '87077': np.int64(140),
 'eg': np.int64(701),
 'england': np.int64(717),
 'try': np.int64(2211),
 'dont miss': np.int64(659),
 'seriously': np.int64(1935),
 'ha': np.int64(965),
 'pay': np.int64(1650),
 'first': np.int64(803),
 'da': np.int64(584),
 'stock': np.int64(2049),
 'comin': np.int64(515),
 'finish': np.int64(802),
 'lunch': np.int64(1300),
 'lor': np.int64(1272),
 'ard': np.int64(234),
 'smth': np.int64(1996),
 'alright': np.int64(196),
 'meet': np.int64(1344),
 'ust': np.int64(2297),
 'eat': np.int64(696),
 'really': np.int64(1787),
 'hungry': np.int64(1064),
 'tho': np.int64(2150),
 'sucks': np.int64(2074),
 'mark': np.int64(1320),
 'know': np.int64(1169),
 'sick': np.int64(1961),
 'turn': np.int64(2223),
 'pizza': np.int64(1682),
 'lol': np.int64(1263),
 'ol': np.int64(1556),
 'always': np.int64(198),
 'id': np.int64(1075),
 'catch': np.int64(443),
 'bus': np.int64(370),
 'egg': np.int64(702),
 'tea': np.int64(2105),
 'mom': np.int64(1410),
 'leave': np.int64(1210),
 'dinner': np.int64(636),
 'love': np.int64(1276),
 'amp': np.int64(203),
 'pack': np.int64(1635),
 'car': np.int64(429),
 'now': np.int64(1515),
 'let': np.int64(1222),
 'there': np.int64(2138),
 'room': np.int64(1861),
 'let know': np.int64(1223),
 'work': np.int64(2446),
 'feel like': np.int64(784),
 'ait': np.int64(185),
 'clear': np.int64(485),
 'sure': np.int64(2085),
 'us': np.int64(2292),
 'eah': np.int64(684),
 'fall': np.int64(767),
 'till': np.int64(2157),
 'you': np.int64(2490),
 'eah get': np.int64(685),
 'go there': np.int64(911),
 'tell': np.int64(2111),
 'anything': np.int64(219),
 'tell anything': np.int64(2112),
 'quick': np.int64(1761),
 'hanks': np.int64(978),
 'subscription': np.int64(2073),
 'ringtone': np.int64(1849),
 'uk': np.int64(2244),
 'charge': np.int64(457),
 'month': np.int64(1416),
 'please': np.int64(1690),
 'confirm': np.int64(528),
 'mobile charge': np.int64(1399),
 'reply yes': np.int64(1825),
 'up': np.int64(2263),
 'look': np.int64(1269),
 'msg': np.int64(1438),
 'again': np.int64(173),
 'learn': np.int64(1206),
 '2nd': np.int64(79),
 'lesson': np.int64(1220),
 'go home': np.int64(905),
 'ops': np.int64(1588),
 'roommate': np.int64(1862),
 'do': np.int64(647),
 'see': np.int64(1907),
 'letter': np.int64(1224),
 'nything': np.int64(1537),
 'decide': np.int64(607),
 'ello': np.int64(707),
 'how': np.int64(1054),
 'saturday': np.int64(1884),
 'texting': np.int64(2125),
 'tomo': np.int64(2178),
 'invite': np.int64(1110),
 'ls': np.int64(1289),
 'ahead': np.int64(179),
 'weekend': np.int64(2386),
 'abiola': np.int64(146),
 'great weekend': np.int64(937),
 'forget': np.int64(816),
 'need': np.int64(1465),
 'crave': np.int64(559),
 'sweet': np.int64(2091),
 'need you': np.int64(1467),
 'burn': np.int64(369),
 'sms': np.int64(1994),
 'nokia': np.int64(1497),
 'camcorder': np.int64(413),
 '08000930705': np.int64(15),
 'delivery': np.int64(616),
 'tomorrow': np.int64(2179),
 'mobile free': np.int64(1402),
 'free camcorder': np.int64(823),
 'please call': np.int64(1691),
 'call 08000930705': np.int64(387),
 'delivery tomorrow': np.int64(617),
 'ho': np.int64(1029),
 'reat': np.int64(1791),
 'hope': np.int64(1042),
 'man': np.int64(1314),
 'well': np.int64(2394),
 'lt': np.int64(1291),
 'gt': np.int64(943),
 'lt gt': np.int64(1293),
 'calls': np.int64(412),
 'messages': np.int64(1356),
 'nigeria': np.int64(1486),
 'air': np.int64(183),
 'on': np.int64(1561),
 'hopefully': np.int64(1044),
 'tyler': np.int64(2238),
 'can': np.int64(419),
 'could': np.int64(551),
 'maybe': np.int64(1336),
 'ask': np.int64(249),
 'bite': np.int64(329),
 'am': np.int64(199),
 'even': np.int64(735),
 'hospital': np.int64(1046),
 'keep': np.int64(1155),
 'weak': np.int64(2373),
 'want go': np.int64(2354),
 'hat': np.int64(989),
 'time': np.int64(2158),
 'saw': np.int64(1888),
 'class': np.int64(483),
 'first time': np.int64(804),
 'run': np.int64(1870),
 'half': np.int64(969),
 'almost': np.int64(193),
 'whole': np.int64(2411),
 'second': np.int64(1902),
 'like lt': np.int64(1237),
 'ride': np.int64(1845),
 'morning': np.int64(1423),
 'place': np.int64(1683),
 'ow': np.int64(1624),
 'never': np.int64(1473),
 'realize': np.int64(1786),
 'it': np.int64(1125),
 'since': np.int64(1970),
 'best': np.int64(316),
 'seem': np.int64(1912),
 'happy': np.int64(984),
 'the': np.int64(2134),
 'sorry': np.int64(2017),
 'give': np.int64(895),
 'ms': np.int64(1437),
 'ac': np.int64(150),
 'new': np.int64(1474),
 'red': np.int64(1798),
 'play': np.int64(1686),
 'ice': np.int64(1074),
 'correct': np.int64(542),
 'end': np.int64(714),
 'yesterday': np.int64(2483),
 'find': np.int64(796),
 'ongrats': np.int64(1566),
 'year': np.int64(2478),
 'special': np.int64(2026),
 'cinema': np.int64(474),
 'pass': np.int64(1647),
 'yours': np.int64(2493),
 'etc': np.int64(733),
 'bx420': np.int64(376),
 'ip4': np.int64(1114),
 '5we': np.int64(117),
 '150pm': np.int64(50),
 'out': np.int64(1620),
 'yours call': np.int64(2494),
 'bx420 ip4': np.int64(377),
 'ip4 5we': np.int64(1115),
 '5we 150pm': np.int64(118),
 'miss out': np.int64(1383),
 'orry': np.int64(1597),
 'later': np.int64(1190),
 'meeting': np.int64(1346),
 'orry call': np.int64(1598),
 'call later': np.int64(397),
 'ell': np.int64(706),
 'reach': np.int64(1780),
 'es': np.int64(730),
 'pick': np.int64(1673),
 'move': np.int64(1429),
 'pain': np.int64(1637),
 'kill': np.int64(1163),
 'way home': np.int64(2371),
 'good': np.int64(920),
 'girls': np.int64(894),
 'situation': np.int64(1980),
 'ts': np.int64(2216),
 'part': np.int64(1643),
 'check': np.int64(466),
 'forever': np.int64(815),
 'come': np.int64(506),
 'double': np.int64(662),
 'hair': np.int64(968),
 'wun': np.int64(2460),
 'cut': np.int64(581),
 'short': np.int64(1956),
 'nice': np.int64(1484),
 'follow': np.int64(810),
 'review': np.int64(1838),
 'mob': np.int64(1392),
 'award': np.int64(274),
 'bonus': np.int64(339),
 'prize call': np.int64(1743),
 'oday': np.int64(1540),
 'song': np.int64(2012),
 'frnds': np.int64(841),
 'rply': np.int64(1866),
 'me send': np.int64(1340),
 'complimentary': np.int64(523),
 'trip': np.int64(2205),
 '1000': np.int64(31),
 'dis': np.int64(640),
 '18': np.int64(53),
 '10': np.int64(26),
 'ur award': np.int64(2269),
 'hear': np.int64(1000),
 'plane': np.int64(1685),
 'lucky': np.int64(1298),
 'save': np.int64(1887),
 'money': np.int64(1415),
 'hee': np.int64(1004),
 'babe': np.int64(284),
 'im': np.int64(1086),
 'wanna': np.int64(2351),
 'something': np.int64(2008),
 'xx': np.int64(2469),
 'where': np.int64(2406),
 'call now': np.int64(401),
 'wait': np.int64(2339),
 'call free': np.int64(394),
 'cool': np.int64(539),
 'respect': np.int64(1829),
 'hat cool': np.int64(990),
 'people': np.int64(1654),
 'much': np.int64(1444),
 'pa': np.int64(1633),
 'oes': np.int64(1542),
 'job': np.int64(1141),
 'ta': np.int64(2097),
 'hi': np.int64(1019),
 'hi hi': np.int64(1020),
 'ou': np.int64(1608),
 'stop': np.int64(2052),
 'urgnt': np.int64(2290),
 'real': np.int64(1785),
 'yo': np.int64(2487),
 'ticket': np.int64(2155),
 'one': np.int64(1562),
 'done': np.int64(656),
 'start': np.int64(2040),
 'bed': np.int64(306),
 'too': np.int64(2189),
 'gotta': np.int64(932),
 'come back': np.int64(507),
 'kano': np.int64(1151),
 'il': np.int64(1084),
 'download': np.int64(665),
 'wen': np.int64(2396),
 'don': np.int64(654),
 'stand': np.int64(2037),
 'close': np.int64(488),
 'll': np.int64(1251),
 'another': np.int64(210),
 'night': np.int64(1487),
 'spend': np.int64(2032),
 'late': np.int64(1189),
 'afternoon': np.int64(170),
 'mean': np.int64(1341),
 'include': np.int64(1096),
 'pleasure': np.int64(1692),
 'smile': np.int64(1991),
 'trouble': np.int64(2206),
 'rain': np.int64(1767),
 'hurt': np.int64(1067),
 'someone': np.int64(2006),
 'smiling': np.int64(1992),
 'lease': np.int64(1207),
 'service': np.int64(1936),
 'representative': np.int64(1827),
 '0800': np.int64(12),
 '10am': np.int64(33),
 'guarantee': np.int64(952),
 '5000': np.int64(110),
 'lease call': np.int64(1208),
 'call customer': np.int64(393),
 'customer service': np.int64(580),
 'service representative': np.int64(1938),
 'guarantee 1000': np.int64(953),
 '1000 cash': np.int64(32),
 'cash 5000': np.int64(438),
 '5000 prize': np.int64(113),
 'avent': np.int64(269),
 'plan': np.int64(1684),
 'buy': np.int64(374),
 'show': np.int64(1957),
 'simply': np.int64(1969),
 'password': np.int64(1648),
 'verify': np.int64(2311),
 'po': np.int64(1705),
 'box': np.int64(351),
 'po box': np.int64(1706),
 'atching': np.int64(257),
 'movie': np.int64(1430),
 'abt': np.int64(149),
 'wat abt': np.int64(2364),
 'load': np.int64(1254),
 'loan': np.int64(1255),
 'wk': np.int64(2435),
 'shower': np.int64(1959),
 'cause': np.int64(444),
 'prob': np.int64(1746),
 'need get': np.int64(1466),
 'get home': np.int64(869),
 'coffee': np.int64(495),
 'nothing': np.int64(1513),
 'else': np.int64(708),
 'kay': np.int64(1153),
 'price': np.int64(1737),
 'long': np.int64(1266),
 'ave': np.int64(267),
 'pick up': np.int64(1675),
 'drive': np.int64(674),
 'test': np.int64(2119),
 'yet': np.int64(2484),
 'guess': np.int64(961),
 'boston': np.int64(347),
 'men': np.int64(1351),
 'change': np.int64(455),
 'cuz': np.int64(583),
 'page': np.int64(1636),
 'life': np.int64(1229),
 'umma': np.int64(2247),
 'lot': np.int64(1274),
 'dear': np.int64(606),
 'love lot': np.int64(1279),
 'wish': np.int64(2427),
 'birthday': np.int64(325),
 'truly': np.int64(2208),
 'ight': np.int64(1082),
 'hit': np.int64(1026),
 'would': np.int64(2456),
 'address': np.int64(164),
 'computer': np.int64(524),
 'old': np.int64(1557),
 'better': np.int64(318),
 'ont': np.int64(1571),
 'worry': np.int64(2451),
 'busy': np.int64(372),
 'oing': np.int64(1550),
 'cos': np.int64(543),
 'things': np.int64(2140),
 'mah': np.int64(1305),
 'ent': np.int64(721),
 'contact': np.int64(530),
 'last': np.int64(1184),
 'draw': np.int64(666),
 'guaranteed': np.int64(954),
 '12hrs': np.int64(41),
 '150ppm': np.int64(51),
 'try contact': np.int64(2212),
 'contact you': np.int64(533),
 'last weekend': np.int64(1188),
 'weekend draw': np.int64(2387),
 'draw show': np.int64(668),
 'prize guaranteed': np.int64(1745),
 'guaranteed call': np.int64(955),
 'valid 12hrs': np.int64(2306),
 'anyway': np.int64(222),
 'fine': np.int64(800),
 'juz': np.int64(1149),
 'tt': np.int64(2219),
 'eatin': np.int64(697),
 'weight': np.int64(2392),
 'haha': np.int64(967),
 'happened': np.int64(982),
 'enter': np.int64(722),
 'cabin': np.int64(380),
 'said': np.int64(1875),
 'boss': np.int64(345),
 'felt': np.int64(785),
 'askd': np.int64(250),
 'apartment': np.int64(223),
 'cabin pa': np.int64(381),
 'pa said': np.int64(1634),
 'said happy': np.int64(1876),
 'happy day': np.int64(986),
 'day boss': np.int64(596),
 'boss felt': np.int64(346),
 'felt special': np.int64(786),
 'special askd': np.int64(2027),
 'askd lunch': np.int64(251),
 'lunch lunch': np.int64(1302),
 'lunch invite': np.int64(1301),
 'invite apartment': np.int64(1111),
 'apartment go': np.int64(224),
 'winner': np.int64(2425),
 'specially': np.int64(2029),
 'holiday': np.int64(1033),
 'inc': np.int64(1094),
 'operator': np.int64(1584),
 'min': np.int64(1361),
 'ou winner': np.int64(1614),
 'winner specially': np.int64(2426),
 'specially select': np.int64(2030),
 'select receive': np.int64(1914),
 'receive 1000': np.int64(1794),
 'speak live': np.int64(2024),
 'live operator': np.int64(1250),
 'operator claim': np.int64(1585),
 'must': np.int64(1452),
 'friday': np.int64(831),
 'mm': np.int64(1388),
 'my': np.int64(1454),
 'uncle': np.int64(2251),
 'inform': np.int64(1102),
 'school': np.int64(1895),
 'directly': np.int64(639),
 'pls': np.int64(1694),
 'food': np.int64(812),
 'rivate': np.int64(1854),
 '2004': np.int64(66),
 'account': np.int64(154),
 'statement': np.int64(2041),
 'points': np.int64(1714),
 'identifier': np.int64(1078),
 'expire': np.int64(756),
 'account statement': np.int64(155),
 'identifier code': np.int64(1079),
 '2000': np.int64(62),
 'caller': np.int64(405),
 '03': np.int64(6),
 'landline': np.int64(1179),
 'rgent mobile': np.int64(1842),
 'award 2000': np.int64(275),
 'bonus caller': np.int64(340),
 'caller prize': np.int64(406),
 'call landline': np.int64(396),
 'ere': np.int64(729),
 'all': np.int64(190),
 'odays': np.int64(1541),
 'voda': np.int64(2326),
 'number': np.int64(1531),
 '350': np.int64(88),
 'match': np.int64(1325),
 '08712300220': np.int64(20),
 'quote': np.int64(1765),
 'standard': np.int64(2038),
 'rat': np.int64(1771),
 'app': np.int64(225),
 'voda number': np.int64(2327),
 'number end': np.int64(1533),
 'receive 350': np.int64(1795),
 '350 award': np.int64(89),
 'match please': np.int64(1326),
 'call 08712300220': np.int64(389),
 '08712300220 quote': np.int64(21),
 'quote claim': np.int64(1766),
 'mu': np.int64(1443),
 'wat time': np.int64(2365),
 'ood': np.int64(1575),
 'bother': np.int64(348),
 'over': np.int64(1623),
 'send text': np.int64(1929),
 'ey': np.int64(760),
 'girl': np.int64(892),
 'del': np.int64(612),
 'bak': np.int64(291),
 'long time': np.int64(1267),
 'give call': np.int64(896),
 'ear': np.int64(689),
 'answer': np.int64(213),
 'unshine': np.int64(2258),
 'quiz': np.int64(1764),
 'top': np.int64(2190),
 'sony': np.int64(2013),
 'dvd': np.int64(683),
 'player': np.int64(1688),
 'country': np.int64(552),
 'in': np.int64(1092),
 '82277': np.int64(130),
 'sp': np.int64(2021),
 'sony dvd': np.int64(2014),
 'ant': np.int64(214),
 'lay': np.int64(1201),
 'dog': np.int64(650),
 'locations': np.int64(1257),
 'direct': np.int64(638),
 'join': np.int64(1143),
 'bt': np.int64(363),
 'txting': np.int64(2235),
 'nt': np.int64(1526),
 'ec2a': np.int64(699),
 'send direct': np.int64(1920),
 'ur mob': np.int64(2280),
 'haf': np.int64(966),
 'yijue': np.int64(2485),
 'msgs': np.int64(1441),
 'chat': np.int64(462),
 'to': np.int64(2170),
 'age': np.int64(174),
 'yr': np.int64(2496),
 'ot': np.int64(1601),
 'lazy': np.int64(1202),
 'type': np.int64(2239),
 'lect': np.int64(1213),
 'ir': np.int64(1118),
 'mail': np.int64(1307),
 'ir wait': np.int64(1119),
 'swt': np.int64(2095),
 'tire': np.int64(2165),
 'little': np.int64(1247),
 'lovable': np.int64(1275),
 'persons': np.int64(1664),
 'coz': np.int64(556),
 'gud': np.int64(956),
 'ni8': np.int64(1483),
 'gud ni8': np.int64(959),
 'are': np.int64(235),
 'open': np.int64(1583),
 'ya': np.int64(2473),
 'sexy': np.int64(1943),
 'local': np.int64(1256),
 'luv': np.int64(1303),
 'ltd': np.int64(1295),
 'per msg': np.int64(1658),
 'reply stop': np.int64(1824),
 'stop end': np.int64(2053),
 'our': np.int64(1619),
 'begin': np.int64(312),
 'qatar': np.int64(1757),
 'pray': np.int64(1732),
 'hard': np.int64(988),
 'delete': np.int64(614),
 'why': np.int64(2412),
 'get job': np.int64(871),
 'wine': np.int64(2424),
 'thk': np.int64(2148),
 'shirt': np.int64(1951),
 'sometimes': np.int64(2010),
 'dream': np.int64(670),
 'without': np.int64(2433),
 'joy': np.int64(1145),
 'tv': np.int64(2224),
 'become': np.int64(305),

## Encoding for Output Feature(label)

In [44]:
y = pd.get_dummies(messages['label'],dtype=int)

In [45]:
y

      ham  spam
0       1     0
1       1     0
2       0     1
3       1     0
4       1     0
...   ...   ...
5567    0     1
5568    1     0
5569    1     0
5570    1     0
5571    1     0

[5572 rows x 2 columns]

In [46]:
y = y.iloc[:,0].values

In [47]:
y

array([1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1], shape=(5572,))

## Train Test Split

In [48]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.20,random_state=42)

## Train Your Model

In [49]:
from sklearn.naive_bayes import MultinomialNB
spamDeduction = MultinomialNB()

In [50]:
spamDeduction.fit(X_train,y_train)

MultinomialNB()

In [51]:
y_pred = spamDeduction.predict(X_test)

In [52]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9874439461883409
              precision    recall  f1-score   support

           0       0.97      0.94      0.95       149
           1       0.99      0.99      0.99       966

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115

In [53]:
import os
import pickle

In [54]:
if not os.path.exists('Model'):
    os.makedirs('Model')

In [55]:
# Save the models
pickle.dump(spamDeduction, open('Model/spamModel.pkl', 'wb'))

# Save the CountVectorizer
pickle.dump(cv, open('Model/vectorizer.pkl', 'wb'))

print("Model and Vectorizer saved successfully!")

Model and Vectorizer saved successfully!